<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-05-02 at 06:38:19.
 */
class newPHPClassTest extends PHPUnit_Framework_TestCase {

    /**
     * @var newPHPClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new newPHPClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
